version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./test.db
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    environment:
      - SQLITE_DATABASE=/data/db.sqlite
    volumes:
      - ./data:/data
